services:
  - type: web
    name: signllm-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m flask run --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: FLASK_APP
        value: backend.py
      - key: FLASK_ENV
        value: production

  - type: static
    name: signllm-frontend
    buildCommand: echo "Static files ready"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /home/home.html 