services:
  # Frontend static site
  - type: web
    name: signai-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_WS_URL
        sync: false

  # WebSocket backend service
  - type: web
    name: signai-websocket
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server/websocket_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: PORT
        value: 10000
    autoDeploy: true
    envVars:
      - key: FIREBASE_API_KEY
        value: AIzaSyB9xPOobDKznWSxkWxTngBarSEOqdjRr74
      - key: FIREBASE_AUTH_DOMAIN
        value: signai-ea820.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: signai-ea820 